// Dwg_HelloWorld.h  file  =================
// generated by pfodWeb Designer Dwg Code Generator
/*
 * (c)2026 Forward Computing and Control Pty. Ltd.
 * NSW Australia, www.forward.com.au
 * This code is not warranted to be fit for any purpose. You may only use it at your own risk.
 * This generated code may be freely used for both private and commercial use
 * provided this copyright is maintained.
 */
#ifndef DWG_HelloWorld_H
#define DWG_HelloWorld_H
// Arduino code for drawing: HelloWorld
// Generated from pfodWeb Designer dwg "HelloWorld"
#include <pfodDrawing.h>

class Dwg_HelloWorld : public pfodDrawing {
  public:
    Dwg_HelloWorld();
    virtual void init();
    bool sendDwg(); // returns true if dwg sent else false i.e. not this dwg's loadCmd
    bool processDwgCmds(); // return true if handled else false
    void sendFullDrawing();
    void sendUpdate();
    unsigned long dwgRefresh_ms;

  protected:
    virtual void sendIndexedItems();
  private:
    bool initialized;

};

// The drawing object the menu code uses.  To add your own behaviour,
// subclass Dwg_HelloWorld, define your own instance, and define this
// function in YOUR .cpp to return it -- the weak default in
// Dwg_HelloWorld.cpp is then replaced at link time and NONE of these
// generated files need editing:
//     MyHelloWorld myHelloWorld;
//     Dwg_HelloWorld& get_dwg_HelloWorld() { return myHelloWorld; }
// The unused default instance then never has init() called on it, so it
// never registers with the parser and never allocates its pfodDwgs.
Dwg_HelloWorld& get_dwg_HelloWorld();
extern Dwg_HelloWorld dwg_HelloWorld; // the default instance
#endif
// ================= end of Dwg_HelloWorld.h  file
