// Dwg_HelloWorld.h  file  =================
// generated by pfodWeb Designer Dwg Code Generator
#ifndef DWG_HelloWorld_H
#define DWG_HelloWorld_H
// Arduino code for drawing: HelloWorld
// Generated from pfodWeb Designer dwg "HelloWorld"
#include <pfodDrawing.h>

class Dwg_HelloWorld : public pfodDrawing {
  public:
    Dwg_HelloWorld();
    void init();
    bool sendDwg(); // returns true if dwg sent else false i.e. not this dwg's loadCmd
    bool processDwgCmds(); // return true if handled else false
    unsigned long dwgRefresh;

  protected:
    void sendFullDrawing();
    void sendUpdate();
    virtual void sendIndexedItems();
  private:
    bool initialized;

};

extern Dwg_HelloWorld dwg_HelloWorld;
#endif
// ================= end of Dwg_HelloWorld.h  file
