// Dwg_LedOnOff.cpp  file ==============
// generated by pfodWeb Designer Dwg Code Generator
/*
 * (c)2026 Forward Computing and Control Pty. Ltd.
 * NSW Australia, www.forward.com.au
 * This code is not warranted to be fit for any purpose. You may only use it at your own risk.
 * This generated code may be freely used for both private and commercial use
 * provided this copyright is maintained.
 */

#include "Dwg_LedOnOff.h"
#include <pfodDebugPtr.h>

//#define DEBUG
static Print* debugPtr = NULL;  // local to this file

Dwg_LedOnOff dwg_LedOnOff;
// weak: defining this function in any other .cpp replaces it, which is
// how a subclass takes over without editing this file -- see Dwg_LedOnOff.h
Dwg_LedOnOff& __attribute__((weak)) get_dwg_LedOnOff() { return dwg_LedOnOff; }

#include "Dwg_LedOn.h"
#include "Dwg_LedOff.h"

Dwg_LedOnOff::Dwg_LedOnOff() {
  initialized = false;
  dwgRefresh_ms = 2000;
}

void Dwg_LedOnOff::init() {
  if (initialized) {
    return;
  }
  initialized = true;
  (void)debugPtr;  // suppress unused warning
#ifdef DEBUG
  debugPtr = getDebugPtr();
#endif
  pfodDrawing::init();
  // Forces this dwg's own pfodAutoIdx/pfodAutoCmd to a fixed,
  // deterministic value at boot instead of leaving it lazily assigned by
  // client request order -- sent to a local discard sink
  // (default-constructed pfodParser leaves io=NULL, so its write()s
  // silently no-op), never a real client. Runs BEFORE the drawings
  // inserted below, so this dwg takes the lower idx values and each
  // child it inserts takes higher ones.
  pfodParser primingSink;
  setParser(&primingSink);
  sendFullDrawing();  // before any included dwgs to match later gets higher idx

  get_dwg_LedOn().init(); // initialize inserted drawing
  get_dwg_LedOff().init(); // initialize inserted drawing
}

// return true if handled else false
// either handle cmd here or in main sketch
bool Dwg_LedOnOff::processDwgCmds() {
  if (!(*(parserPtr->getDwgCmd()))) {  // ==> getDwgCmd returned pointer to empty string
    return false; // not dwg cmd, not handled
  }
  return false; // not handled
}

bool Dwg_LedOnOff::sendDwg() {
  if (!parserPtr->cmdEquals(*this)) {
    return false; // not this dwg's loadCmd
  }  // else
  if (parserPtr->isRefresh()) { // refresh just send update
    sendUpdate();
  } else {
    sendFullDrawing();
  }
  return true;
}

// all the indexed items are included here, edit as needed for updates
void Dwg_LedOnOff::sendIndexedItems() {
    dwgsPtr->label().idx(idx_1).color(dwgsPtr->BLACK).text("Led is Off").bold().offset(20,11.5).center().decimals(2).send();
}

void Dwg_LedOnOff::sendFullDrawing() {
    // Start the drawing
    dwgsPtr->start(40, 15, dwgsPtr->SILVER);
    parserPtr->sendRefreshAndVersion(dwgRefresh_ms); // sets version and refresh time for dwg pfodWeb processes this
    dwgsPtr->pushZero(-8, -3, 0.7);
    dwgsPtr->insertDwg().loadCmd(get_dwg_LedOn()).offset(0,0).send();
    dwgsPtr->pushZero(29, 0, 1);
    dwgsPtr->insertDwg().loadCmd(get_dwg_LedOff()).offset(0,0).send();
    dwgsPtr->popZero();
    dwgsPtr->popZero();
    dwgsPtr->index().idx(idx_1).send(); // place holder for indexed item
    sendIndexedItems(); // update indexed items with their real values
    dwgsPtr->end();
}

// only indexed items can be sent as an update
// all the indexed items are included here, edit as needed
void Dwg_LedOnOff::sendUpdate() {
    dwgsPtr->startUpdate();
    sendIndexedItems(); // send updated indexed items
    dwgsPtr->end();
}
// ============== end of Dwg_LedOnOff.cpp  file
