// Dwg_LedOnOff.h  file  =================
// generated by pfodWeb Designer Dwg Code Generator
/*
 * (c)2026 Forward Computing and Control Pty. Ltd.
 * NSW Australia, www.forward.com.au
 * This code is not warranted to be fit for any purpose. You may only use it at your own risk.
 * This generated code may be freely used for both private and commercial use
 * provided this copyright is maintained.
 */
#ifndef DWG_LedOnOff_H
#define DWG_LedOnOff_H
// Arduino code for drawing: LedOnOff
// Generated from pfodWeb Designer dwg "LedOnOff"
#include <pfodDrawing.h>

class Dwg_LedOnOff : public pfodDrawing {
  public:
    Dwg_LedOnOff();
    void init();
    bool sendDwg(); // returns true if dwg sent else false i.e. not this dwg's loadCmd
    bool processDwgCmds(); // return true if handled else false
    void sendFullDrawing();
    void sendUpdate();
    unsigned long dwgRefresh;

  protected:
    virtual void sendIndexedItems();
  private:
    bool initialized;
    pfodAutoIdx idx_1;

};

extern Dwg_LedOnOff dwg_LedOnOff;
#endif
// ================= end of Dwg_LedOnOff.h  file
