// Dwg_LedOff.h  file  =================
// generated by pfodWeb Designer Dwg Code Generator
/*
 * (c)2026 Forward Computing and Control Pty. Ltd.
 * NSW Australia, www.forward.com.au
 * This code is not warranted to be fit for any purpose. You may only use it at your own risk.
 * This generated code may be freely used for both private and commercial use
 * provided this copyright is maintained.
 */
#ifndef DWG_LedOff_H
#define DWG_LedOff_H
// Arduino code for drawing: LedOff
// Generated from pfodWeb Designer dwg "LedOff"
#include <pfodDrawing.h>

class Dwg_LedOff : public pfodDrawing {
  public:
    Dwg_LedOff();
    virtual void init();
    bool sendDwg(); // returns true if dwg sent else false i.e. not this dwg's loadCmd
    bool processDwgCmds(); // return true if handled else false
    void sendFullDrawing();
    void sendUpdate();
    unsigned long dwgRefresh_ms;

  protected:
    virtual void sendIndexedItems();
    virtual bool Dwg_LedOff_cmd_c1(int row, int col, uint8_t touchType, const byte* editedText); // touchZone cmd_c1 touched, return true if handled
    pfodAutoIdx idx_1;
    pfodAutoIdx idx_2;
    pfodAutoCmd cmd_c1;
  private:
    bool initialized;

};

// The drawing object the menu code uses.  To add your own behaviour,
// subclass Dwg_LedOff, define your own instance, and define this
// function in YOUR .cpp to return it -- the weak default in
// Dwg_LedOff.cpp is then replaced at link time and NONE of these
// generated files need editing:
//     MyLedOff myLedOff;
//     Dwg_LedOff& get_dwg_LedOff() { return myLedOff; }
// The unused default instance then never has init() called on it, so it
// never registers with the parser and never allocates its pfodDwgs.
Dwg_LedOff& get_dwg_LedOff();
extern Dwg_LedOff dwg_LedOff; // the default instance
#endif
// ================= end of Dwg_LedOff.h  file
