// Board: FireBeetle 2 ESP32-E
// Connection: ble

/* Code generated by pfodWeb V4.1.9-- 2nd Sept 2026
 * (c)2026 Forward Computing and Control Pty. Ltd.
 * NSW Australia, www.forward.com.au
 * This code is not warranted to be fit for any purpose. You may only use it at your own risk.
 * This generated code may be freely used for both private and commercial use
 * provided this copyright is maintained.
 */
#ifndef PFOD_MAIN_MENU_H
#define PFOD_MAIN_MENU_H
// pfodMainMenu.h

#include <pfodParser.h>
typedef void (*pfodCloseConnectionPtr)(Stream *);  // the pointer to the method that handles parser closeConnection calls

class pfodMainMenu {
  public:
    pfodMainMenu();
    virtual void init(pfodCloseConnectionPtr _closeConnectionFnPtr = NULL);
    virtual void sendMainMenu(pfodParser &parser);
    virtual void sendMainMenuUpdate(pfodParser &parser);
    virtual void handle(pfodParser &parser);
  protected:
    pfodAutoCmd dwgMenuItem_LedOnOff_Cmd; // drawing menu item
  private:
    bool initialized;
    pfodCloseConnectionPtr closeConnectionFnPtr;
};

// entry points used by the main sketch
typedef  void (*handle_mainMenuFnPtr)(pfodParser & parser);
handle_mainMenuFnPtr init_pfodMainMenu(pfodCloseConnectionPtr = NULL);
void handle_pfodMainMenu(pfodParser & parser);

// The main menu object the sketch runs.  To add your own behaviour,
// subclass pfodMainMenu, define your own instance, and define this
// function in YOUR .cpp to return it -- the weak default in
// pfodMainMenu.cpp is then replaced at link time and NONE of these
// generated files need editing:
//     MyMainMenu myMainMenu;
//     pfodMainMenu& get_pfodMainMenu() { return myMainMenu; }
// The unused default instance then never has init() called on it.
pfodMainMenu& get_pfodMainMenu();
extern pfodMainMenu mainMenu; // the default instance
#endif
