// Board: Arduino UNO
// Connection: Serial @ 115200 baud

/* Code generated by pfodWeb V4.1.9-- 2nd Sept 2026
 * (c)2026 Forward Computing and Control Pty. Ltd.
 * NSW Australia, www.forward.com.au
 * This code is not warranted to be fit for any purpose. You may only use it at your own risk.
 * This generated code may be freely used for both private and commercial use
 * provided this copyright is maintained.
 */
#ifndef PFOD_MAIN_MENU_H
#define PFOD_MAIN_MENU_H
// pfodMainMenu.h

#include <pfodParser.h>
typedef void (*pfodCloseConnectionPtr)(Stream *);  // the pointer to the method that handles parser closeConnection calls

class pfodMainMenu {
  public:
    pfodMainMenu();
    virtual void init(pfodCloseConnectionPtr _closeConnectionFnPtr = NULL);
    virtual void sendMainMenu(pfodParser &parser);
    virtual void sendMainMenuUpdate(pfodParser &parser);
    virtual void handle(pfodParser &parser);
    virtual void tickCharts(pfodParser &parser); // streams this level's own charts + every nested sub-menu's
    virtual void chart_Voltage_Plot_sendData(pfodParser &parser);
  protected:
    virtual void onPwmSettingChanged(int value);
    virtual void onLedIsChanged(int value);
    virtual void chart_Voltage_Plot_readPlotData();
    pfodAutoCmd datadisplay_A0_Cmd; // datadisplay -- 'A0'
    pfodAutoCmd label__Cmd_2; // label -- 'label'
    pfodAutoCmd onoffdisplay_Door_is_Cmd; // onoffdisplay -- 'Door is'
    pfodAutoCmd label__Cmd; // label -- 'label'
    pfodAutoCmd pwm_PWM_Setting_Cmd; // pwm -- 'PWM Setting'
    pfodAutoCmd onoff_LED_is_Cmd; // onoff -- 'LED is'
    pfodAutoCmd chart_Voltage_Plot_Cmd; // chart -- 'Voltage Plot'
    pfodAutoCmd submenu_Submenu_Cmd; // submenu -- 'Submenu'
  private:
    bool initialized;
    pfodCloseConnectionPtr closeConnectionFnPtr;
};

// entry points used by the main sketch
typedef  void (*handle_mainMenuFnPtr)(pfodParser & parser);
handle_mainMenuFnPtr init_pfodMainMenu(pfodCloseConnectionPtr = NULL);
void handle_pfodMainMenu(pfodParser & parser);

// The main menu object the sketch runs.  To add your own behaviour,
// subclass pfodMainMenu, define your own instance, and define this
// function in YOUR .cpp to return it -- the weak default in
// pfodMainMenu.cpp is then replaced at link time and NONE of these
// generated files need editing:
//     MyMainMenu myMainMenu;
//     pfodMainMenu& get_pfodMainMenu() { return myMainMenu; }
// The unused default instance then never has init() called on it.
pfodMainMenu& get_pfodMainMenu();
extern pfodMainMenu mainMenu; // the default instance
#endif
