// Board: Arduino UNO
// Connection: Serial @ 115200 baud

/* Code generated by pfodWeb V4.1.7-- 23th August 2026
 * (c)2026 Forward Computing and Control Pty. Ltd.
 * NSW Australia, www.forward.com.au
 * This code is not warranted to be fit for any purpose. You may only use it at your own risk.
 * This generated code may be freely used for both private and commercial use
 * provided this copyright is maintained.
 */
// SubMenu_Submenu.cpp -- generated by pfodWeb Generate Code
// Arduino code for sub-menu: Submenu

#include "SubMenu_Submenu.h"

static const unsigned long refresh_ms = 0;


SubMenu_Submenu subMenu_Submenu;
// weak: defining this function in any other .cpp replaces it, which is
// how a subclass takes over without editing this file -- see SubMenu_Submenu.h
SubMenu_Submenu& __attribute__((weak)) get_subMenu_Submenu() { return subMenu_Submenu; }

void SubMenu_Submenu::onSubmenuButtonPressed(pfodParser &parser) {
  // << add your action code here for this button
  parser.print(F("{}")); // change this return as needed.
}

SubMenu_Submenu::SubMenu_Submenu() {
  initialized = false;
}

void SubMenu_Submenu::init() {
  if (initialized) {
    return;
  }
  initialized = true;
}

void SubMenu_Submenu::sendMenu(pfodParser& parser) {
  parser.menu();  // start a Menu screen pfod message.  Send {,
  parser.print(F("<bg y>~Example Submenu")); // background yellow
  parser.sendRefreshAndVersion(refresh_ms);
  parser.button(button_Submenu_Button_Cmd); // start Button -- 'Submenu Button'
  parser.print(F("<bg w><b><m>")); // background white, bold, m text
  parser.print(F("~Submenu Button"));
  parser.endOfMsg();
}

void SubMenu_Submenu::sendMenuUpdate(pfodParser& parser) {
  parser.menuUpdate();  // start an Update Menu pfod message. Send {;
  parser.button(button_Submenu_Button_Cmd); // start Button
  parser.endOfMsg();
}

bool SubMenu_Submenu::handleCmd(pfodParser &parser, uint8_t cmd, uint8_t *pfodFirstArg, long *pfodLongRtn) {
  (void)cmd;
  if (false) {
    // never taken -- keeps every real branch below in a uniform "} else if" shape
  } else if(parser.cmdEquals(button_Submenu_Button_Cmd)) { // user pressed -- 'Submenu Button'
    onSubmenuButtonPressed(parser); // virtual hook -- must send a pfod response
    return true;
  }
  return false;
}

