// Board: Arduino UNO
// Connection: Serial @ 115200 baud

/* Code generated by pfodWeb V4.1.9-- 2nd Sept 2026
 * (c)2026 Forward Computing and Control Pty. Ltd.
 * NSW Australia, www.forward.com.au
 * This code is not warranted to be fit for any purpose. You may only use it at your own risk.
 * This generated code may be freely used for both private and commercial use
 * provided this copyright is maintained.
 */
#ifndef SUBMENU_SUBMENU_H
#define SUBMENU_SUBMENU_H
// SubMenu_Submenu.h -- generated by pfodWeb Generate Code, fully
// mechanical/regenerated -- see SubMenu_Submenu.cpp for hook bodies.
#include <pfodParser.h>

class SubMenu_Submenu {
  public:
    SubMenu_Submenu();
    virtual void init();
    virtual void sendMenu(pfodParser &parser);
    virtual void sendMenuUpdate(pfodParser &parser);
    virtual bool handleCmd(pfodParser &parser, uint8_t cmd, uint8_t *pfodFirstArg, long *pfodLongRtn);
  protected:
    virtual void onSubmenuButtonPressed(pfodParser &parser); // must send a pfod response
    pfodAutoCmd button_Submenu_Button_Cmd; // button -- 'Submenu Button'
  private:
    bool initialized;
};

// The sub-menu object its parent menu uses.  To add your own behaviour,
// subclass SubMenu_Submenu, define your own instance, and define this
// function in YOUR .cpp to return it -- the weak default in
// SubMenu_Submenu.cpp is then replaced at link time and NONE of these
// generated files need editing:
//     MySubMenu_Submenu mySubMenu_Submenu;
//     SubMenu_Submenu& get_subMenu_Submenu() { return mySubMenu_Submenu; }
// The unused default instance then never has init() called on it.
SubMenu_Submenu& get_subMenu_Submenu();
extern SubMenu_Submenu subMenu_Submenu; // the default instance
#endif
