// Dwg_LedOn.cpp  file ==============
// generated by pfodWeb Designer Dwg Code Generator
/*
 * (c)2026 Forward Computing and Control Pty. Ltd.
 * NSW Australia, www.forward.com.au
 * This code is not warranted to be fit for any purpose. You may only use it at your own risk.
 * This generated code may be freely used for both private and commercial use
 * provided this copyright is maintained.
 */

#include "Dwg_LedOn.h"
#include <pfodDebugPtr.h>

extern void turnLedOn();

//#define DEBUG
static Print* debugPtr = NULL;  // local to this file

Dwg_LedOn dwg_LedOn;


bool Dwg_LedOn::Dwg_LedOn_cmd_c1(int row, int col, uint8_t touchType, const byte* editedText) {
  (void)row; (void)col; (void)touchType; (void)editedText; // suppress warnings
  turnLedOn();
  // sendUpdate from here
  // and return true,  if only this dwg needs updating
  //  sendUpdate(); 
  //  return true;
  // else return false to propagate upto the mainmenu to let it send the response.
  return false; 
}

Dwg_LedOn::Dwg_LedOn() {
  initialized = false;
  dwgRefresh = 0;
}

void Dwg_LedOn::init() {
  if (initialized) {
    return;
  }
  initialized = true;
  (void)debugPtr;  // suppress unused warning
#ifdef DEBUG
  debugPtr = getDebugPtr();
#endif
  pfodDrawing::init();
}

// return true if handled else false
// either handle cmd here or in main sketch
bool Dwg_LedOn::processDwgCmds() {
  if (!(*(parserPtr->getDwgCmd()))) {  // ==> getDwgCmd returned pointer to empty string
    return false; // not dwg cmd, not handled
  }
  if (parserPtr->dwgCmdEquals(cmd_c1)) { // handle touchZone cmd_c1
    return Dwg_LedOn_cmd_c1(parserPtr->getTouchedRow(), parserPtr->getTouchedCol(), parserPtr->getTouchType(), parserPtr->getEditedText());
  }
  return false; // not handled
}

bool Dwg_LedOn::sendDwg() {
  if (!parserPtr->cmdEquals(*this)) {
    return false; // not this dwg's loadCmd
  }  // else
  if (parserPtr->isRefresh()) { // refresh just send update
    sendUpdate();
  } else {
    sendFullDrawing();
  }
  return true;
}

// all the indexed items are included here, edit as needed for updates
void Dwg_LedOn::sendIndexedItems() {
    dwgsPtr->rectangle().filled().centered().rounded().idx(idx_1).color(dwgsPtr->LIME).size(18,7).offset(25,12.5).send();
    dwgsPtr->label().idx(idx_2).color(dwgsPtr->RED).text("Turn Led On").bold().offset(25,12.5).center().decimals(2).send();
}

void Dwg_LedOn::sendFullDrawing() {
    // Start the drawing
    dwgsPtr->start(50, 25, dwgsPtr->BLUE);
    parserPtr->sendRefreshAndVersion(dwgRefresh); // sets version and refresh time for dwg pfodWeb processes this
    dwgsPtr->index().idx(idx_1).send(); // place holder for indexed item
    dwgsPtr->index().idx(idx_2).send(); // place holder for indexed item
    dwgsPtr->touchZone().cmd(cmd_c1).centered().size(18,7).offset(25,12.5).send();
    dwgsPtr->touchAction().cmd(cmd_c1).action(dwgsPtr->rectangle().filled().centered().idx(idx_1).color(dwgsPtr->SILVER).size(18,7).offset(25,12.5)).send();
    sendIndexedItems(); // update indexed items with their real values
    dwgsPtr->end();
}

// only indexed items can be sent as an update
// all the indexed items are included here, edit as needed
void Dwg_LedOn::sendUpdate() {
    dwgsPtr->startUpdate();
    sendIndexedItems(); // send updated indexed items
    dwgsPtr->end();
}
// ============== end of Dwg_LedOn.cpp  file
