// Dwg_LedOff.h  file  =================
// generated by pfodWeb Designer Dwg Code Generator
/*
 * (c)2026 Forward Computing and Control Pty. Ltd.
 * NSW Australia, www.forward.com.au
 * This code is not warranted to be fit for any purpose. You may only use it at your own risk.
 * This generated code may be freely used for both private and commercial use
 * provided this copyright is maintained.
 */
#ifndef DWG_LedOff_H
#define DWG_LedOff_H
// Arduino code for drawing: LedOff
// Generated from pfodWeb Designer dwg "LedOff"
#include <pfodDrawing.h>

class Dwg_LedOff : public pfodDrawing {
  public:
    Dwg_LedOff();
    void init();
    bool sendDwg(); // returns true if dwg sent else false i.e. not this dwg's loadCmd
    bool processDwgCmds(); // return true if handled else false
    void sendFullDrawing();
    void sendUpdate();
    unsigned long dwgRefresh;

  protected:
    virtual void sendIndexedItems();
    virtual bool Dwg_LedOff_cmd_c1(int row, int col, uint8_t touchType, const byte* editedText); // touchZone cmd_c1 touched, return true if handled
  private:
    bool initialized;
    pfodAutoIdx idx_1;
    pfodAutoIdx idx_2;
    pfodAutoCmd cmd_c1;

};

extern Dwg_LedOff dwg_LedOff;
#endif
// ================= end of Dwg_LedOff.h  file
